[package]
name = "db-creator"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
simd-json.workspace = true
ahash.workspace = true
jemallocator = "0.5.4"
